[Writable]
LogLevel = "INFO"

[Service]
Port = 59989
StartupMsg = "device llrp started"

[MessageBus]
SecretName = "redisdb"
  [MessageBus.Topics]
  PublishTopicPrefix = "edgex/events/device" # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix
  CommandRequestTopic = "edgex/device/command/request/device-rfid-llrp/#"   # subscribing for inbound command requests
  CommandResponseTopicPrefix = "edgex/device/command/response"   # publishing outbound command responses; <device-service>/<device-name>/<command-name>/<method> will be added to this publish topic prefix
  [MessageBus.Optional]
  # Default MQTT Specific options that need to be here to enable environment variable overrides of them
  ClientId = "device-rfid-llrp"

[Device]
ProvisionWatchersDir = "./res/provision_watchers"
DevicesDir = ""
  [Device.Discovery]
  Enabled = true
  Interval = "1h"

[AppCustom]
# List of IPv4 subnets to perform LLRP discovery process on, in CIDR format (X.X.X.X/Y)
# separated by commas ex: "192.168.1.0/24,10.0.0.0/24"
DiscoverySubnets = ""

# Maximum simultaneous network probes
ProbeAsyncLimit = 4000

# Maximum amount of seconds to wait for each IP probe before timing out.
# This will also be the minimum time the discovery process can take.
ProbeTimeoutSeconds = 2

# Port to scan for LLRP devices on
ScanPort = "5084"

# Maximum amount of seconds the discovery process is allowed to run before it will be cancelled.
# It is especially important to have this configured in the case of larger subnets such as /16 and /8
MaxDiscoverDurationSeconds = 300
